package calculadora;


public class Calculadora extends javax.swing.JFrame {
    double num1 = 0, num2 = 0, result = 0;
    String operator = "";

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }
    
    private void concatNumberToConsole(int n) {
        if (this.operator.equals(txtResultConsole.getText())
                || "Error".equals(txtResultConsole.getText())
                || "0".equals(txtResultConsole.getText())) {
            txtResultConsole.setText("");
        }
        
        if(String.valueOf(this.result).equals(txtResultConsole.getText())) {
            clearAll();
        }
        
        txtResultConsole.setText(txtResultConsole.getText().concat(String.valueOf(n)));
    }
    
    private void initOperation(String symbol) {
        double currentNum;
        
        try {
            currentNum = Double.parseDouble(txtResultConsole.getText());
        } catch (NumberFormatException e) {
            txtResultConsole.setText("Error");
            return;
        }
        
        if (this.num1 == 0 || currentNum == this.result) {
            this.num1 = currentNum;
        } else {
            if ("/".equals(this.operator) && currentNum == 0) {
                txtResultConsole.setText("Error");
                return;
            } else {
                this.num1 = doCurrentOperation(this.num1, currentNum, this.operator);
            }
        }
        
        txtResultConsole.setText(String.valueOf(symbol));
        this.operator = symbol;
    }
    
    private void clearAll() {
        this.num1 = 0;
        this.num2 = 0;
        this.result = 0;
        this.operator = "";
        txtResultConsole.setText("");
    }
    
    private double doCurrentOperation(Double n, Double m, String sym) {
        double res = 0;
        if (null == sym) {
            return res;
        } else switch (sym) {
            case "+":
                res = n + m;
                break;
            case "-":
                res = n - m;
                break;
            case "*":
                res = n * m;
                break;
            case "/":
                res = n / m;
                break;
            default:
                return res;
        }
        return res;
    }
    
    private void calcTotalResult () {
        
        if ("".equals(this.operator)) {
            return;
        }
        
        if (String.valueOf(this.result).equals(txtResultConsole.getText())) {
            this.result = doCurrentOperation(this.result, this.num2, this.operator);
            txtResultConsole.setText(String.valueOf(this.result));
            return;
        }
        
        try {
            this.num2 = Double.parseDouble(txtResultConsole.getText());
        } catch (NumberFormatException e) {
            txtResultConsole.setText("Error");
            return;
        }
        
        if ("/".equals(this.operator) && this.num2 == 0) {
            txtResultConsole.setText("Error");
            return;
        }
        
        this.result = doCurrentOperation(this.num1, this.num2, this.operator);
        txtResultConsole.setText(String.valueOf(this.result));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResultConsole = new javax.swing.JTextField();
        btnPlus = new javax.swing.JButton();
        btnDigitOne = new javax.swing.JButton();
        btnDigitTwo = new javax.swing.JButton();
        btnDigitThree = new javax.swing.JButton();
        btnDigitFour = new javax.swing.JButton();
        btnDigitFive = new javax.swing.JButton();
        btnDigitSix = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnDigitSeven = new javax.swing.JButton();
        btnDigitEight = new javax.swing.JButton();
        btnDigitNine = new javax.swing.JButton();
        btnTimes = new javax.swing.JButton();
        btnClearConsole = new javax.swing.JButton();
        btnDigitZero = new javax.swing.JButton();
        btnDividedBy = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        txtResultConsole.setEditable(false);
        txtResultConsole.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        txtResultConsole.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultConsole.setPreferredSize(new java.awt.Dimension(335, 50));

        btnPlus.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnPlus.setText("+");
        btnPlus.setPreferredSize(new java.awt.Dimension(80, 80));
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnDigitOne.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDigitOne.setText("1");
        btnDigitOne.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDigitOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitOneActionPerformed(evt);
            }
        });

        btnDigitTwo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDigitTwo.setText("2");
        btnDigitTwo.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDigitTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitTwoActionPerformed(evt);
            }
        });

        btnDigitThree.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDigitThree.setText("3");
        btnDigitThree.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDigitThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitThreeActionPerformed(evt);
            }
        });

        btnDigitFour.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDigitFour.setText("4");
        btnDigitFour.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDigitFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitFourActionPerformed(evt);
            }
        });

        btnDigitFive.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDigitFive.setText("5");
        btnDigitFive.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDigitFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitFiveActionPerformed(evt);
            }
        });

        btnDigitSix.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDigitSix.setText("6");
        btnDigitSix.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDigitSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitSixActionPerformed(evt);
            }
        });

        btnMinus.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnMinus.setText("-");
        btnMinus.setPreferredSize(new java.awt.Dimension(80, 80));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnDigitSeven.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDigitSeven.setText("7");
        btnDigitSeven.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDigitSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitSevenActionPerformed(evt);
            }
        });

        btnDigitEight.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDigitEight.setText("8");
        btnDigitEight.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDigitEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitEightActionPerformed(evt);
            }
        });

        btnDigitNine.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDigitNine.setText("9");
        btnDigitNine.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDigitNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitNineActionPerformed(evt);
            }
        });

        btnTimes.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnTimes.setText("*");
        btnTimes.setPreferredSize(new java.awt.Dimension(80, 80));
        btnTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimesActionPerformed(evt);
            }
        });

        btnClearConsole.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnClearConsole.setText("C");
        btnClearConsole.setPreferredSize(new java.awt.Dimension(80, 80));
        btnClearConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearConsoleActionPerformed(evt);
            }
        });

        btnDigitZero.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDigitZero.setText("0");
        btnDigitZero.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDigitZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigitZeroActionPerformed(evt);
            }
        });

        btnDividedBy.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnDividedBy.setText("/");
        btnDividedBy.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDividedBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividedByActionPerformed(evt);
            }
        });

        btnEquals.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnEquals.setText("=");
        btnEquals.setPreferredSize(new java.awt.Dimension(80, 80));
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDigitOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigitTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigitThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDigitFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigitFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigitSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDigitSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigitEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigitNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClearConsole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigitZero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDividedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtResultConsole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDigitOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigitTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigitThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDigitFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigitFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigitSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDigitSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigitEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigitNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClearConsole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigitZero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDividedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDigitZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitZeroActionPerformed
        concatNumberToConsole(0);
    }//GEN-LAST:event_btnDigitZeroActionPerformed

    private void btnDigitOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitOneActionPerformed
        concatNumberToConsole(1);
    }//GEN-LAST:event_btnDigitOneActionPerformed

    private void btnDigitTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitTwoActionPerformed
        concatNumberToConsole(2);
    }//GEN-LAST:event_btnDigitTwoActionPerformed

    private void btnDigitThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitThreeActionPerformed
        concatNumberToConsole(3);
    }//GEN-LAST:event_btnDigitThreeActionPerformed

    private void btnDigitFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitFourActionPerformed
        concatNumberToConsole(4);
    }//GEN-LAST:event_btnDigitFourActionPerformed

    private void btnDigitFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitFiveActionPerformed
        concatNumberToConsole(5);
    }//GEN-LAST:event_btnDigitFiveActionPerformed

    private void btnDigitSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitSixActionPerformed
        concatNumberToConsole(6);
    }//GEN-LAST:event_btnDigitSixActionPerformed

    private void btnDigitSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitSevenActionPerformed
        concatNumberToConsole(7);
    }//GEN-LAST:event_btnDigitSevenActionPerformed

    private void btnDigitEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitEightActionPerformed
        concatNumberToConsole(8);
    }//GEN-LAST:event_btnDigitEightActionPerformed

    private void btnDigitNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigitNineActionPerformed
        concatNumberToConsole(9);
    }//GEN-LAST:event_btnDigitNineActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        initOperation("+");
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        initOperation("-");
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimesActionPerformed
        initOperation("*");
    }//GEN-LAST:event_btnTimesActionPerformed

    private void btnDividedByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividedByActionPerformed
        initOperation("/");
    }//GEN-LAST:event_btnDividedByActionPerformed

    private void btnClearConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearConsoleActionPerformed
        clearAll();
    }//GEN-LAST:event_btnClearConsoleActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        calcTotalResult();
    }//GEN-LAST:event_btnEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearConsole;
    private javax.swing.JButton btnDigitEight;
    private javax.swing.JButton btnDigitFive;
    private javax.swing.JButton btnDigitFour;
    private javax.swing.JButton btnDigitNine;
    private javax.swing.JButton btnDigitOne;
    private javax.swing.JButton btnDigitSeven;
    private javax.swing.JButton btnDigitSix;
    private javax.swing.JButton btnDigitThree;
    private javax.swing.JButton btnDigitTwo;
    private javax.swing.JButton btnDigitZero;
    private javax.swing.JButton btnDividedBy;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnTimes;
    private javax.swing.JTextField txtResultConsole;
    // End of variables declaration//GEN-END:variables
}
